name: LightLogin
main: cn.lanink.lightlogin.LightLogin
version: "0.0.1-SNAPSHOT"
api:
  - "1.0.11"
author: "LT_Name"
load: POSTWORLD
softdepend:
  - "MemoriesOfTime-GameCore"
  - "EasyMySQL"
  - "AutoUpData"